### PR TITLE
#685: navbar transparent on mobile devices

### LINKED ISSUE #685: Navbar Is Transparent On Mobile Devices
**Describe the bug**
Navbar is Transparent In Sign Up page . Can't see options.

**To Reproduce**
1. Go to 'https://igboapi.com/'
2. Switch To Mobile View. e.g Pixel 5
3. Click on 'Get an API Key' you will redirected to "https://igboapi.com/signup"
4. Open Navbar 
5. See Issue

**Screenshots**
image
image

**Expected behavior**
image

### PR DESCRIPTION
**Pull request by Ebugo**
## Describe your changes

Fixed transparent navbar on mobile devices for signup page.

## Issue ticket number and link
Closed #685  

## Screenshots (if appropriate):

image

### CODE REVIEW

File: src/pages/signup.js [hunk 1]
```diff
@@ -2,6 +2,7 @@ import React, { useEffect, useState } from 'react';
 import axios from 'axios';
 import { useTranslation } from 'react-i18next';
 import { useForm, Controller } from 'react-hook-form';
+import useMediaQuery from '@material-ui/core/useMediaQuery';
```
Comment (ijemmao) [inline src/pages/signup.js:5]: let's use Chakra UI breakpoints instead: https://chakra-ui.com/docs/hooks/use-breakpoint-value

**Review by ijemmao — CHANGES_REQUESTED** [review]
looking great! just one comment to use Chakra UI over material

File: src/pages/signup.js (hunk 1 above)
Comment (Ebugo) [reply src/pages/signup.js]: Okay, done @ijemmao
